plugins {
    id 'application'
}

repositories {
    mavenCentral()
}

testing {
    suites {
        test {
            useJUnitJupiter('6.0.1')
        }
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    mainClass = 'com.ajay.transactionledger.Main'
}
